language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.6


env:
  global:
    # List package dependencies for conda
    - CONDA_DEPS="pytest numpy"
    # package name for test invocation
    - PACKAGENAME="test"

before_install:
# Here we download miniconda and install the dependencies
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda create -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- conda install $CONDA_DEPS

install:
- pip install -e bugdoc_api

script:
- pytest $PACKAGENAME
